UNIFAC = [
("CH3", "[CH3;X4]"),
("CH2", "[CH2;X4]"),
("CH", "[CH1;X4]"),
("C", ["[CH0;X4]", "[CH0;X3]"]),
("CH2=CH", "[CH2]=[CH]"),
("CH=CH", "[CH]=[CH]"),
("CH2=C", ["[CH2]=[C]", "[CH2]=[c]"]),
("CH=C", ["[CH]=[CH0]", "[CH]=[cH0]"]),
("ACH", "[cH]"),
("AC", "[cH0]"),
("ACCH3", "[c][CH3;X4]"),
("ACCH2", "[c][CH2;X4]"),
("ACCH", "[c][CH;X4]"),
('OH', "[OH]"),
('CH3OH', "[CH3][OH]"),
('H2O', "[OH2]"),
('ACOH', "[c][OH]"),
("CH3CO", "[CH3][CH0]=O"),
("CH2CO", "[CH2][CH0]=O"),
("CH=O", "[CH]=O"),
("CH3COO", "[CH3]C(=O)[OH0]"),
("CH2COO", "[CH2]C(=O)[OH0]"),
("HCOO", "[CH](=O)[OH0]"),
("CH3O", "[CH3][OH0]"),
("CH2O", "[CH2][OH0]"),
("CHO", "[CH][OH0]"),
("THF", "[CH2;R][OH0]"),
("CH3NH2", "[CH3][NH2]"),
("CH2NH2", "[CH2][NH2]"),
("CHNH2", "[CH][NH2]"),
("CH3NH", "[CH3][NH]"),
("CH2NH", "[CH2][NH]"),
("CHNH", "[CH][NH]"),
("CH3N",  ["[CH3][N]", "[CH3][n]"]),
("CH2N", "[CH2][N]"),
("ACNH2", "[c][NH2]"),
("C5H5N", "n1[cH][cH][cH][cH][cH]1"),
("C5H4N", ["n1[c][cH][cH][cH][cH]1",
           "n1[cH][c][cH][cH][cH]1",
           "n1[cH][cH][c][cH][cH]1"]),
('C5H3N', ["n1[c][c][cH][cH][cH]1",
           "n1[c][cH][c][cH][cH]1",
           "n1[c][cH][cH][c][cH]1",
           "n1[c][cH][cH][cH][c]1",
           "n1[cH][c][c][cH][cH]1",
           "n1[cH][c][cH][c][cH]1"]),
("CH3CN", "[CH3]C#N"),
("CH2CN", "[CH2]C#N"),
("COOH", "C(=O)[OH]"),
("HCOOH", "[CH](=O)[OH]"),
("CH2Cl", "[CH2]Cl"),
("CHCl", "[CH]Cl"),
("CCl", "[CH0]Cl"),
("CH2Cl2", "[CH2](Cl)Cl"),
("CHCl2", "[CH](Cl)Cl"),
("CCl2", "C(Cl)Cl"),
("CHCl3", "[CH](Cl)(Cl)Cl"),
("CCl3", "C(Cl)(Cl)(Cl)"),
("CCl4", "C(Cl)(Cl)(Cl)(Cl)"),
("ACCl", "[c]Cl"),
("CH3NO2", "[CH3][N+](=O)[O-]"),
("CH2NO2", "[CH2][N+](=O)[O-]"),
("CHNO2", "[CH][N+](=O)[O-]"),
("ACNO2", "[c][N+](=O)[O-]"),
("CS2", "C(=S)=S"),
("CH3SH", "[CH3][SH]"),
("CH2SH", "[CH2][SH]"),
("Furfural", "O=[CH]c1[cH][cH][cH]o1"),
("DOH", "[OH][CH2][CH2][OH]"),
("I", "[IH0]"),
("Br", "[BrH0]"),
("CH#C", "[CH]#C"),
("C#C", "C#C"),
("DMSO", "[CH3]S(=O)[CH3]"),
("ACRY", "[CH2]=[CH1][C]#N"),
("Cl(C=C)", "[$(Cl[C]=[C])]"),
("C=C", "[CH0]=[CH0]"),
("ACF", "[c]F"),
("DMF", "[CH](=O)N([CH3])[CH3]"),
("HCON(CH2)2", ["[CH](=O)N([CH2])[CH2]", "[CH](=O)N([CH2])[CH3]"]),
("CF3", "C(F)(F)F"),
("CF2", "C(F)F"),
("CF", "[C]F"),
("COO", ["[CH0](=O)[OH0]", "[cH0](=O)[oH0]"]),  
("SiH3", "[SiH3]"),
("SiH2", "[SiH2]"),
("SiH", "[SiH]"),
("Si", "[Si]"),
("SiH2O", "[SiH2][OH0]"),
("SiHO", "[SiH][OH0]"),
("SiO", "[Si][OH0]"),
("NMP", "[CH3]N1[CH2][CH2][CH2]C(=O)1"),
("CCl3F", "C(Cl)(Cl)(Cl)F"),
("CCl2F", "C(Cl)(Cl)F"),
("HCCl2F", "[CH](Cl)(Cl)F"),
("HCClF", "[CH](Cl)F"),
("CClF2", "C(Cl)(F)F"),
("HCClF2", "[CH](Cl)(F)F"),
("CClF3", "C(Cl)(F)(F)F"),
("CCl2F2", "C(Cl)(Cl)(F)F"),
("CONH2", "C(=O)[NH2]"),
("CONHCH3", "C(=O)[NH][CH3]"),
("CONHCH2", "C(=O)[NH][CH2]"),
("CON(CH3)2", "C(=O)N([CH3])[CH3]"),
("CONCH3CH2", "C(=O)N([CH3])[CH2]"),
("CON(CH2)2", "C(=O)N([CH2])[CH2]"),
("C2H5O2", "[OH0;!$(OC=O);!R][CH2;!R][CH2;!R][OH]"),
("C2H4O2", ["[OH0;!$(OC=O);!R][CH;!R][CH2;!R][OH]",
              "[OH0;!$(OC=O);!R][CH2;!R][CH;!R][OH]"]),
("CH3S", "[CH3]S"),
("CH2S", "[CH2]S"),
("CHS", "[CH]S"),
("MORPH", "[CH2]1[CH2][NH][CH2][CH2]O1"),
("C4H4S", "[cH]1[cH][s;X2][cH][cH]1"),
('C4H3S', ["[c]1[cH][s;X2][cH][cH]1",
           "[cH]1[c][s;X2][cH][cH]1"]),
('C4H2S', ["[c]1[c][s;X2][cH][cH]1",
           "[c]1[cH][s;X2][cH][c]1",
           "[cH]1[c][s;X2][c][cH]1",
           "[cH]1[c][s;X2][cH][c]1"]),
("NCO", "N=C=O"),
("H2COCH", "[CH2]1[CH]O1"),
("HCOCH", "[CH]1[CH]O1"),
("COCH", "C1[CH]O1"),
("H2COCH2", "[CH2]1[CH2]O1"),
("OCOCO", "C(=O)OC(=O)"),
("(CH3O)2CO", "[CH3]OC(=O)O[CH3]"),
("(CH2O)2CO", "[CH2]OC(=O)O[CH2]"),
("CH3OCH2OCO", "[CH3]OC(=O)O[CH2]"),
("(CH2)2SU", "[CH2]S(=O)(=O)[CH2]"),
("CH2CHSU", "[CH2]S(=O)(=O)[CH]")]

UNIFAC_TDE = [
("CH3", "[CH3;X4]"),
("CH2", "[CH2;X4]"),
("CH", "[CH1;X4]"),
("C", ["[CH0;X4]", "[CH0;X3]"]),
("CH2=CH", "[CH2]=[CH]"),
("CH=CH", "[CH]=[CH]"),
("CH2=C", ["[CH2]=[C]", "[CH2]=[c]"]),
("CH=C", ["[CH]=[CH0]", "[CH]=[cH0]"]),
("ACH", "[cH]"),
("AC", "[cH0]"),
("ACCH3", "[c][CH3;X4]"),
("ACCH2", "[c][CH2;X4]"),
("ACCH", "[c][CH;X4]"),
('OH', "[OH]"),
('CH3OH', "[CH3][OH]"),
('H2O', "[OH2]"),
('ACOH', "[c][OH]"),
("CH3CO", "[CH3][CH0]=O"),
("CH2CO", "[CH2][CH0]=O"),
("CH=O", "[CH]=O"),
("CH3COO", "[CH3]C(=O)[OH0]"),
("CH2COO", "[CH2]C(=O)[OH0]"),
("HCOO", "[CH](=O)[OH0]"),
("CH3O", "[CH3][OH0]"),
("CH2O", "[CH2][OH0]"),
("CHO", "[CH][OH0]"),
("THF", "[CH2;R][OH0]"),
("CH3NH2", "[CH3][NH2]"),
("CH2NH2", "[CH2][NH2]"),
("CHNH2", "[CH][NH2]"),
("CH3NH", "[CH3][NH]"),
("CH2NH", "[CH2][NH]"),
("CHNH", "[CH][NH]"),
("CH3N",  ["[CH3][N]", "[CH3][n]"]),
("CH2N", "[CH2][N]"),
("ACNH2", "[c][NH2]"),
("C5H5N", "n1[cH][cH][cH][cH][cH]1"),
("C5H4N", ["n1[c][cH][cH][cH][cH]1", "n1[cH][c][cH][cH][cH]1", "n1[cH][cH][c][cH][cH]1"]),
('C5H3N', ["n1[c][c][cH][cH][cH]1", "n1[c][cH][c][cH][cH]1", "n1[c][cH][cH][c][cH]1", "n1[c][cH][cH][cH][c]1", "n1[cH][c][c][cH][cH]1", "n1[cH][c][cH][c][cH]1"]),
("CH3CN", "[CH3]C#N"),
("CH2CN", "[CH2]C#N"),
("COOH", "C(=O)[OH]"),
("HCOOH", "[CH](=O)[OH]"),
("CH2Cl", "[CH2]Cl"),
("CHCl", "[CH]Cl"),
("CCl", "[CH0]Cl"),
("CH2Cl2", "[CH2](Cl)Cl"),
("CHCl2", "[CH](Cl)Cl"),
("CCl2", "C(Cl)Cl"),
("CHCl3", "[CH](Cl)(Cl)Cl"),
("CCl3", "C(Cl)(Cl)(Cl)"),
("CCl4", "C(Cl)(Cl)(Cl)(Cl)"),
("ACCl", "[c]Cl"),
("CH3NO2", "[CH3][N+](=O)[O-]"),
("CH2NO2", "[CH2][N+](=O)[O-]"),
("CHNO2", "[CH][N+](=O)[O-]"),
("ACNO2", "[c][N+](=O)[O-]"),
("CS2", "C(=S)=S"),
("CH3SH", "[CH3][SH]"),
("CH2SH", "[CH2][SH]"),
("Furfural", "O=[CH]c1[cH][cH][cH]o1"),
("DOH", "[OH][CH2][CH2][OH]"),
("I", "[IH0]"),
("Br", "[BrH0]"),
("CH#C", "[CH]#C"),
("C#C", "C#C"),
("DMSO", "[CH3]S(=O)[CH3]"),
("ACRY", "[CH2]=[CH1][C]#N"),
("Cl(C=C)", "[$(Cl[C]=[C])]"),
("C=C", "[CH0]=[CH0]"),
("ACF", "[c]F"),
("DMF", "[CH](=O)N([CH3])[CH3]"),
("HCON(CH2)2", ["[CH](=O)N([CH2])[CH2]", "[CH](=O)N([CH2])[CH3]"]),
("CF3", "C(F)(F)F"),
("CF2", "C(F)F"),
("CF", "[C]F"),
("COO", ["[CH0](=O)[OH0]", "[cH0](=O)[oH0]"]),  
("SiH3", "[SiH3]"),
("SiH2", "[SiH2]"),
("SiH", "[SiH]"),
("Si", "[Si]"),
("SiH2O", "[SiH2][OH0]"),
("SiHO", "[SiH][OH0]"),
("SiO", "[Si][OH0]"),
("NMP", "[CH3]N1[CH2][CH2][CH2]C(=O)1"),
("CCl3F", "C(Cl)(Cl)(Cl)F"),
("CCl2F", "C(Cl)(Cl)F"),
("HCCl2F", "[CH](Cl)(Cl)F"),
("HCClF", "[CH](Cl)F"),
("CClF2", "C(Cl)(F)F"),
("HCClF2", "[CH](Cl)(F)F"),
("CClF3", "C(Cl)(F)(F)F"),
("CCl2F2", "C(Cl)(Cl)(F)F"),
("CONH2", "C(=O)[NH2]"),
("CONHCH3", "C(=O)[NH][CH3]"),
("CONHCH2", "C(=O)[NH][CH2]"),
("CON(CH3)2", "C(=O)N([CH3])[CH3]"),
("CONCH3CH2", "C(=O)N([CH3])[CH2]"),
("CON(CH2)2", "C(=O)N([CH2])[CH2]"),
("C2H5O2", "[OH0;!$(OC=O);!R][CH2;!R][CH2;!R][OH]"),
("C2H4O2", ["[OH0;!$(OC=O);!R][CH;!R][CH2;!R][OH]", "[OH0;!$(OC=O);!R][CH2;!R][CH;!R][OH]"]),
("CH3S", "[CH3]S"),
("CH2S", "[CH2]S"),
("CHS", "[CH]S"),
("MORPH", "[CH2]1[CH2][NH][CH2][CH2]O1"),
("C4H4S", "[cH]1[cH][s;X2][cH][cH]1"),
('C4H3S', ["[c]1[cH][s;X2][cH][cH]1", "[cH]1[c][s;X2][cH][cH]1"]),
('C4H2S', ["[c]1[c][s;X2][cH][cH]1", "[c]1[cH][s;X2][cH][c]1", "[cH]1[c][s;X2][c][cH]1", "[cH]1[c][s;X2][cH][c]1"]),
('(CH2)2SU', '[CH2]S(=O)(=O)[CH2]'),
('CH2CHSU', '[CH2]S(=O)(=O)[CH]'),
('H2COCH2', '[CH2]1[CH2]O1'),
('H2COCH', '[CH2]1[CH]O1'),
('H2COC', '[CH2]1[CH0]O1'),
('HCOCH', '[CH]1[CH]O1'),
('COCH', '[CH0]1[CH]O1'),
('COC', '[CH0]1[CH0]O1'),
('OCOCO', 'C(=O)OC(=O)'),
('ACCN', 'cC#N'),
('ACBr', 'cBr'),
('NCO', 'N=C=O'),
('ACNCO', 'cN=C=O')
]

# SMARTS strings must be syntactically correct and #Idk if this is right: use recursive smarts ($ to specify connections to parts that aren't group). Number of Hs and charges are taken literally from smarts strings, so if not no Hs or charge of 0, the smarts must include that.
MARGAN = [
("CH3", "[CX4H3]"),
("CH2", "[CX4H2]"),
("CH", "[CX4H1]"),
("C", "[CX4H0]"),
("CH2=CH", "[CH2]=[CH]"),
("CH=CH", "[CH]=[CH]"),
("CH2=C", "[CH2]=[CX3]"),
("CH=C", "[CH]=[CX3]"),
("C=C", "[CX3]=[CX3]"),
("CH2=C=CH", "[CH2]=[C]=[CH]"),
("CH2=C=C", "[CH2]=[C]=[CX3]"),
("CH=C=CH", "[CH]=[C]=[CH]"),
("CH#C", "[CH]#[C]"),
("C#C", "[CX2]#[CX2]"),
("aCH", "[cH]"),
("aC fused with aromatic ring", "[c;R2;$(c(:a)(:a):a)]"),
("aC fused with nonaromatic subring", "[c;R2;$(c~[!a])]"),
("aC except as above", "[c;R1]"),
("aN in aromatic ring", "[n]"),
("aC-CH3", "c[CX4H3]"),
("aC-CH2", "c[CX4H2]"),
("aC-CH", "c[CX4H1]"),
("aC-C", "c[CX4H0]"),
("aC-CH=CH2", "c[CH]=[CH2]"),
("aC-CH=CH", "c[CH]=[CH]"),
("aC-C=CH2", "c[CX3]=[CH2]"),
("aC-C#CH", "c[C]#[CH]"),
("aC-C#C", "c[C]#[C]"),
("OH", "[OH;$(*[!c])]"),
("aC-OH", "c[OX2H]"),
("COOH", "[CX3;$(*[!c])](=O)[OX2H]"),
("aC-COOH", "c[CX3](=O)[OX2H]"),
("CH3CO", "[CX4H3][CX3](=O)"),
("CH2CO", "[CX4H2][CX3](=O)"),
("CHCO", "[CX4H1][CX3](=O)"),
("CCO", "[CX4H0][CX3](=O)"),
("aC-CO", "c[CX3](=O)"),
("CHO", "[CX3H1;$(*[!c])]=O"),
("aC-CHO", "c[CX3H1]=O"),
("CH3COO", "[CX4H3][CX3](=O)[OX2]"),
("CH2COO", "[CX4H2][CX3](=O)[OX2]"),
("CHCOO", "[CX4H1][CX3](=O)[OX2]"),
("CCOO", "[CX4H0][CX3](=O)[OX2]"),
("HCOO", "[CX3H1](=O)[OX2]"),
("aC-COO", "c[CX3](=O)[OX2]"),
("aC-OOCH", "c[OX2][CX3H1]=O"),
("aC-OOC", "c[OX2][CX3](=O)"),
("COO except as above", "[CX3;$(*[!c])](=O)[OX2;$(*[!c])]"),
("CH3O", "[CX4H3][OX2]"),
("CH2O", "[CX4H2][OX2]"),
("CH-O", "[CX4H1][OX2]"),
("C-O", "[CX4H0][OX2]"),
("aC-O", "c[OX2]"),
("CH2NH2", "[CX4H2][NX3H2]"),
("CHNH2", "[CX4H1][NX3H2]"),
("CNH2", "[CX4H0][NX3H2]"),
("CH3NH", "[CX4H3][NX3H1]"),
("CH2NH", "[CX4H2][NX3H1]"),
("CHNH", "[CX4H1][NX3H1]"),
("CH3N", "[CX4H3][NX3]"),
("CH2N", "[CX4H2][NX3]"),
("aC-NH2", "c[NX3H2]"),
("aC-NH", "c[NX3H1]"),
("aC-N", "c[NX3]"),
("NH2 except as above", "[NX3H2;$(*[!c])]"),
("CH=N", "[CH]=[NX2]"),
("C=N", "[CX3]=[NX2]"),
("CH2CN", "[CX4H2][C]#[N]"),
("CHCN", "[CX4H1][C]#[N]"),
("CCN", "[CX4H0][C]#[N]"),
("aC-CN", "c[C]#[N]"),
("CN except as above", "[C;$(*[!c])]#[N]"),
("CH2NCO", "[CX4H2][NX2]=[C]=[O]"),
("CHNCO", "[CX4H1][NX2]=[C]=[O]"),
("CNCO", "[CX4H0][NX2]=[C]=[O]"),
("aC-NCO", "c[NX2]=[C]=[O]"),
("CH2NO2", "[CX4H2][NX3+](=O)[O-]"),
("CHNO2", "[CX4H1][NX3+](=O)[O-]"),
("CNO2", "[CX4H0][NX3+](=O)[O-]"),
("aC-NO2", "c[NX3+](=O)[O-]"),
("NO2 except as above", "[NX3+;$(*[!c])](=O)[O-]"),
("ONO", "[OX2][NX2]=O"),
("ONO2", "[OX2][NX3+](=O)[OX1-]"),
("HCON(CH2)2", "[CX3H1](=O)N([CX4H2])[CX4H2]"),
("HCONHCH2", "[CX3H1](=O)[NX3H1][CX4H2]"),
("CONH2", "[CX3;$(*[!c])](=O)[NX3H2]"),
("CONHCH3", "[CX3](=O)[NX3H1][CX4H3]"),
("CONHCH2", "[CX3](=O)[NX3H1][CX4H2]"),
("CON(CH3)2", "[CX3](=O)N([CX4H3])[CX4H3]"),
("CONCH3CH2", "[CX3](=O)N([CX4H3])[CX4H2]"),
("CON(CH2)2", "[CX3](=O)N([CX4H2])[CX4H2]"),
("CONHCO", "[CX3](=O)[NX3H1][CX3]=O"),
("CONCO", "[CX3](=O)[NX3][CX3]=O"),
("aC-CONH2", "c[CX3](=O)[NX3H2]"),
("aC-NH(CO)H", "c[NX3H1][CX3H1]=O"),
("aC-N(CO)H", "c[NX3]([CX3H1]=O)"),
("aC-CONH", "c[CX3](=O)[NX3H1]"),
("aC-NHCO", "c[NX3H1][CX3]=O"),
("aC-NCO", "c[NX3][CX3]=O"),
("NHCONH", "[NX3H1;$(*[!c])][CX3](=O)[NX3H1;$(*[!c])]"),
("NH2CONH", "[NX3H2][CX3](=O)[NX3H1]"),
("NH2CON", "[NX3H2][CX3](=O)[NX3]"),
("NHCON", "[NX3H1][CX3](=O)[NX3]"),
("NCON", "[NX3][CX3](=O)[NX3]"),
("aC-NHCONH2", "c[NX3H1][CX3](=O)[NX3H2]"),
("aC-NHCONH", "c[NX3H1][CX3](=O)[NX3H1]"),
("NHCO except as above", "[NX3H1;$(*[!c])][CX3;$(*[!c])](=O)"),
("CH2Cl", "[CX4H2]Cl"),
("CHCl", "[CX4H1]Cl"),
("CCl", "[CX4H0]Cl"),
("CHCl2", "[CX4H1](Cl)Cl"),
("CCl2", "[CX4H0](Cl)Cl"),
("CCl3", "[CX4H0](Cl)(Cl)Cl"),
("CH2F", "[CX4H2]F"),
("CHF", "[CX4H1]F"),
("CF", "[CX4H0]F"),
("CHF2", "[CX4H1](F)F"),
("CF2", "[CX4H0](F)F"),
("CF3", "[CX4H0](F)(F)F"),
("CCl2F", "[CX4H0](Cl)(Cl)F"),
("HCClF", "[CX4H1](Cl)F"),
("CClF2", "[CX4H0](Cl)(F)F"),
("aC-Cl", "cCl"),
("aC-F", "cF"),
("aC-I", "cI"),
("aC-Br", "cBr"),
("I- except as above", "[I;!$(*c)]"),
("Br- except as above", "[Br;!$(*c)]"),
("F- except as above", "[F;!$(*c)]"),
("Cl- except as above", "[Cl;!$(*c)]"),
("CHNOH", "[CH]=[NX2][OX2H]"),
("CNOH", "[CX3]=[NX2][OH]"),
("aC-CHNOH", "c[CH]=[NX2][OX2H]"),
("OCH2CH2OH", "[OX2][CH2][CH2][OX2H]"),
("OCHCH2OH", "[OX2][CH]([CH2][OX2H])"),
("OCH2CHOH", "[OX2][CH2][CH]([OX2H])"),
("-O-OH", "[OX2][OX2H]"),
("CH2SH", "[CX4H2][SX2H]"),
("CHSH", "[CX4H1][SX2H]"),
("CSH", "[CX4H0][SX2H]"),
("aC-SH", "c[SX2H]"),
("-SH ( except as above)", "[SX2H;$(*[!c])]"),
("CH3S", "[CX4H3][SX2]"),
("CH2S", "[CX4H2][SX2]"),
("CHS", "[CX4H1][SX2]"),
("CS", "[CX4H0][SX2]"),
("aC-S-", "c[SX2]"),
("SO", "[SX3;$(*[!c])](=O)"),
("SO2", "[SX4;$(*[!c])](=O)(=O)"),
("SO3 (sulfite)", "O=S([O;$(*[#6])])[O;$(*[#6])]"),
("SO3 (sulfonate)", "[S;$(*[#6])](=O)(=O)[O;$(*[#6])]"),
("SO4 (sulfate)", "O=[S](=O)([O;$(*[#6])])[O;$(*[#6])]"),
("aC-SO", "c[SX3](=O)"),
("aC-SO2", "c[SX4](=O)(=O)"),
("PH (phosphine)", "[PH1]"),
("P (phosphine)", "[PH0]"),
("PO3 (phosphite)", "[P]([O;$(*[#6])])([O;$(*[#6])])[O;$(*[#6])]"),
("PHO3 (phosphonate)", "[PH1](=O)(O)O"),
("PO3 (phosphonate)", "[P;$(*[#6])](=O)([O;$(*[#6])])[O;$(*[#6])]"),
("PHO4 (phosphate)", "O[P](=O)([OH1])O"),
("PO4 (phosphate)", "O=[P]([O;$(*[#6])])([O;$(*[#6])])[O;$(*[#6])]"),
("aC-PO4", "c[OX2H0]P(=O)(O)(O)"),
("aC-P", "cP"),
("CO3 (carbonate)", "O=[C]([O;$(*[#6])])[O;$(*[#6])]"),
("C2H3O", "[O;R]1[CH1;R][CH2;R]1"),
("C2H2O", ["[O;R]1[CH2;R][CH0;R]1", "[O;R]1[CH1;R][CH1;R]1"]),
("C2O", "[OX2;R]1[CH1X4;R][CX4;R]1"),
("CH2 (cyclic)", "[CH2;R]"),
("CH (cyclic)", "[CH;R]"),
("C (cyclic)", "[C;R]"),
("CH=CH (cyclic)", "[CH;R]=[CH;R]"),
("CH=C (cyclic)", "[CH;R]=[C;R]"),
("C=C (cyclic)", "[C;R]=[C;R]"),
("CH2=C (cyclic)", "[CH2]=[C;R]"),
("NH (cyclic)", "[NH;R]"),
("N (cyclic)", "[N;R]"),
("CH=N (cyclic)", "[CH;R]=[N;R]"),
("C=N (cyclic)", "[C;R]=[N;R]"),
("O (cyclic)", "[O;R]"),
("CO (cyclic)", "[C;R]=O"),
("S (cyclic)", "[S;R]"),
("SO2 (cyclic)", "[S;R](=O)=O"),
]

MARGAN_GEM = [
    ("CH3", "[CH3X4]"),
    ("CH2", "[CH2X4]"),
    ("CH", "[CHX4]"),
    ("C", "[CX4]"),
    ("CH2=CH", "[CH2X3]=[CHX3]"),
    ("CH=CH", "[CHX3]=[CHX3]"),
    ("CH2=C", "[CH2X3]=[CX3]"),
    ("CH=C", "[CHX3]=[CX3]"),
    ("C=C", "[CX3]=[CX3]"),
    ("CH2=C=CH", "[CH2X3]=[CX2]=[CHX3]"),
    ("CH2=C=C", "[CH2X3]=[CX2]=[CX3]"),
    ("CH=C=CH", "[CHX3]=[CX2]=[CHX3]"),
    ("CH#C", "[CHX2]#[CX2]"),
    ("C#C", "[CX2]#[CX2]"),
    ("aCH", "[cH]"),
    ("aC fused with aromatic ring", "[c;R2;$(c~a)]"),
    ("aC fused with nonaromatic subring", "[c;R2;$(c~[!a])]"),
    ("aC except as above", "[c;!R2]"),
    ("aN in aromatic ring", "[n]"),
    ("aC-CH3", "c[CH3X4]"),
    ("aC-CH2", "c[CH2X4]"),
    ("aC-CH", "c[CHX4]"),
    ("aC-C", "c[CX4]"),
    ("aC-CH=CH2", "c[CHX3]=[CH2X3]"),
    ("aC-CH=CH", "c[CHX3]=[CHX3]"),
    ("aC-C=CH2", "c[CX3]=[CH2X3]"),
    ("aC-C#CH", "c[CX2]#[CHX2]"),
    ("aC-C#C", "c[CX2]#[CX2]"),
    ("OH", "[OX2H]"),
    ("aC-OH", "c[OX2H]"),
    ("COOH", "[CX3](=O)[OX2H]"),
    ("aC-COOH", "c[CX3](=O)[OX2H]"),
    ("CH3CO", "[CH3X4][CX3]=O"),
    ("CH2CO", "[CH2X4][CX3]=O"),
    ("CHCO", "[CHX4][CX3]=O"),
    ("CCO", "[CX4][CX3]=O"),
    ("aC-CO", "c[CX3]=O"),
    ("CHO", "[CHX3]=O"),
    ("aC-CHO", "c[CHX3]=O"),
    ("CH3COO", "[CH3X4][CX3](=O)[OX2]"),
    ("CH2COO", "[CH2X4][CX3](=O)[OX2]"),
    ("CHCOO", "[CHX4][CX3](=O)[OX2]"),
    ("CCOO", "[CX4][CX3](=O)[OX2]"),
    ("HCOO", "[CHX3](=O)[OX2]"),
    ("aC-COO", "c[CX3](=O)[OX2]"),
    ("aC-OOCH", "c[OX2][CHX3]=O"),
    ("aC-OOC", "c[OX2][CX3]=O"),
    ("COO except as above", "[CX3;$(*[!c])](=O)[OX2;$(*[!c])]"),
    ("CH3O", "[CH3X4][OX2]"),
    ("CH2O", "[CH2X4][OX2]"),
    ("CH-O", "[CHX4][OX2]"),
    ("C-O", "[CX4][OX2]"),
    ("aC-O", "c[OX2]"),
    ("CH2NH2", "[CH2X4][NX3H2]"),
    ("CHNH2", "[CHX4][NX3H2]"),
    ("CNH2", "[CX4][NX3H2]"),
    ("CH3NH", "[CH3X4][NX3H]"),
    ("CH2NH", "[CH2X4][NX3H]"),
    ("CHNH", "[CHX4][NX3H]"),
    ("CH3N", "[CH3X4][NX3]"),
    ("CH2N", "[CH2X4][NX3]"),
    ("aC-NH2", "c[NX3H2]"),
    ("aC-NH", "c[NX3H]"),
    ("aC-N", "c[NX3]"),
    ("NH2 except as above", "[NX3H2;$(*[!c])]"),
    ("CH=N", "[CHX3]=[NX2]"),
    ("C=N", "[CX3]=[NX2]"),
    ("CH2CN", "[CH2X4]C#N"),
    ("CHCN", "[CHX4]C#N"),
    ("CCN", "[CX4]C#N"),
    ("aC-CN", "cC#N"),
    ("CN except as above", "[CX2;$(*[!c])]#N"),
    ("CH2NCO", "[CH2X4]N=C=O"),
    ("CHNCO", "[CHX4]N=C=O"),
    ("CNCO", "[CX4]N=C=O"),
    ("aC-NCO", "cN=C=O"),
    ("CH2NO2", "[CH2X4][NX3+](=O)[O-]"),
    ("CHNO2", "[CHX4][NX3+](=O)[O-]"),
    ("CNO2", "[CX4][NX3+](=O)[O-]"),
    ("aC-NO2", "c[NX3+](=O)[O-]"),
    ("NO2 except as above", "[NX3+;$(*[!c])](=O)[O-]"),
    ("ONO", "[OX2]N=O"),
    ("ONO2", "[OX2][NX3+](~[O-])=O"),
    ("HCON(CH2)2", "[CHX3](=O)N([CH2X4])[CH2X4]"),
    ("HCONHCH2", "[CHX3](=O)[NX3H][CH2X4]"),
    ("CONH2", "[CX3](=O)[NX3H2]"),
    ("CONHCH3", "[CX3](=O)[NX3H][CH3X4]"),
    ("CONHCH2", "[CX3](=O)[NX3H][CH2X4]"),
    ("CON(CH3)2", "[CX3](=O)N([CH3X4])[CH3X4]"),
    ("CONCH3CH2", "[CX3](=O)N([CH3X4])[CH2X4]"),
    ("CON(CH2)2", "[CX3](=O)N([CH2X4])[CH2X4]"),
    ("CONHCO", "[CX3](=O)[NX3H][CX3]=O"),
    ("CONCO", "[CX3](=O)[NX3][CX3]=O"),
    ("aC-CONH2", "c[CX3](=O)[NX3H2]"),
    ("aC-NH(CO)H", "c[NX3H][CHX3]=O"),
    ("aC-N(CO)H", "c[NX3][CHX3]=O"),
    ("aC-CONH", "c[CX3](=O)[NX3H]"),
    ("aC-NHCO", "c[NX3H][CX3]=O"),
    ("aC-NCO", "c[NX3][CX3]=O"),
    ("NHCONH", "[NX3H][CX3](=O)[NX3H]"),
    ("NH2CONH", "[NX3H2][CX3](=O)[NX3H]"),
    ("NH2CON", "[NX3H2][CX3](=O)[NX3]"),
    ("NHCON", "[NX3H][CX3](=O)[NX3]"),
    ("NCON", "[NX3][CX3](=O)[NX3]"),
    ("aC-NHCONH2", "c[NX3H][CX3](=O)[NX3H2]"),
    ("aC-NHCONH", "c[NX3H][CX3](=O)[NX3H]"),
    ("NHCO except as above", "[NX3H;$(*[!c])][CX3;$(*[!c])]=O"),
    ("CH2Cl", "[CH2X4]Cl"),
    ("CHCl", "[CHX4]Cl"),
    ("CCl", "[CX4]Cl"),
    ("CHCl2", "[CHX4](Cl)Cl"),
    ("CCl2", "[CX4](Cl)Cl"),
    ("CCl3", "[CX4](Cl)(Cl)Cl"),
    ("CH2F", "[CH2X4]F"),
    ("CHF", "[CHX4]F"),
    ("CF", "[CX4]F"),
    ("CHF2", "[CHX4](F)F"),
    ("CF2", "[CX4](F)F"),
    ("CF3", "[CX4](F)(F)F"),
    ("CCl2F", "[CX4](Cl)(Cl)F"),
    ("HCClF", "[CHX4](Cl)F"),
    ("CClF2", "[CX4](Cl)(F)F"),
    ("aC-Cl", "cCl"),
    ("aC-F", "cF"),
    ("aC-I", "cI"),
    ("aC-Br", "cBr"),
    ("I- except as above", "[I;$(*[!c])]"),
    ("Br- except as above", "[Br;$(*[!c])]"),
    ("F- except as above", "[F;$(*[!c])]"),
    ("Cl- except as above", "[Cl;$(*[!c])]"),
    ("CHNOH", "[CHX3]=N[OX2H]"),
    ("CNOH", "[CX3]=N[OX2H]"),
    ("aC-CHNOH", "c[CHX3]=N[OX2H]"),
    ("OCH2CH2OH", "[OX2][CH2X4][CH2X4][OX2H]"),
    ("OCHCH2OH", "[OX2][CHX4][CH2X4][OX2H]"),
    ("OCH2CHOH", "[OX2][CH2X4][CHX4][OX2H]"),
    ("-O-OH", "[OX2][OX2H]"),
    ("CH2SH", "[CH2X4][SX2H]"),
    ("CHSH", "[CHX4][SX2H]"),
    ("CSH", "[CX4][SX2H]"),
    ("aC-SH", "c[SX2H]"),
    ("-SH ( except as above)", "[SX2H;$(*[!c])]"),
    ("CH3S", "[CH3X4][SX2]"),
    ("CH2S", "[CH2X4][SX2]"),
    ("CHS", "[CHX4][SX2]"),
    ("CS", "[CX4][SX2]"),
    ("aC-S-", "c[SX2]"),
    ("SO", "[SX3]=O"),
    ("SO2", "[SX4](=O)=O"),
    ("SO3 (sulfite)", "[SX3](=O)([OX2])[OX2]"),
    ("SO3 (sulfonate)", "[SX4](=O)(=O)[OX2]"),
    ("SO4 (sulfate)", "[SX4](=O)(=O)([OX2])[OX2]"),
    ("aC-SO", "c[SX3]=O"),
    ("aC-SO2", "c[SX4](=O)=O"),
    ("PH (phosphine)", "[PX3H]"),
    ("P (phosphine)", "[PX3]"),
    ("PO3 (phosphite)", "[PX3]([OX2])([OX2])[OX2]"),
    ("PHO3 (phosphonate)", "[PX4H](=O)([OX2])[OX2]"),
    ("PO3 (phosphonate)", "[PX4](=O)([OX2])[OX2]"),
    ("PHO4 (phosphate)", "[PX4](=O)([OX2H])([OX2])[OX2]"),
    ("PO4 (phosphate)", "[PX4](=O)([OX2])([OX2])[OX2]"),
    ("aC-PO4", "c[OX2][PX4](=O)([OX2])[OX2]"),
    ("aC-P", "c[P]"),
    ("CO3 (carbonate)", "[CX3](=O)([OX2])[OX2]"),
    ("C2H3O in three member ring", "[O;R]1[CH2;R][CH1;R]1"),
    ("C2H2O in three member ring", ['[O;R]1[CH1;R][CH1;R]1', '[O;R]1[CH2;R][CH0;R]1']),
    ("C2O in three member ring", "[O;R]1[C;R][C;R]1"),
    ("CH2 (cyclic)", "[CH2X4;R]"),
    ("CH (cyclic)", "[CHX4;R]"),
    ("C (cyclic)", "[CX4;R]"),
    ("CH=CH (cyclic)", "[CHX3;R]=[CHX3;R]"),
    ("CH=C (cyclic)", "[CHX3;R]=[CX3;R]"),
    ("C=C (cyclic)", "[CX3;R]=[CX3;R]"),
    ("CH2=C (cyclic)", "[CH2X3]=[CX3;R]"),
    ("NH (cyclic)", "[NH;R]"),
    ("N (cyclic)", "[N;R]"),
    ("CH=N (cyclic)", "[CHX3;R]=[NX2;R]"),
    ("C=N (cyclic)", "[CX3;R]=[NX2;R]"),
    ("O (cyclic)", "[O;R]"),
    ("CO (cyclic)", "[CX3;R]=O"),
    ("S (cyclic)", "[S;R]"),
    ("SO2 (cyclic)", "[SX4;R](=O)=O"),
]