MARGAN = [
    ("CH3", "[CH3X4]"),
    ("CH2", "[CH2X4]"),
    ("CH", "[CHX4]"),
    ("C", "[CX4]"),
    ("CH2=CH", "[CH2X3]=[CHX3]"),
    ("CH=CH", "[CHX3]=[CHX3]"),
    ("CH2=C", "[CH2X3]=[CX3]"),
    ("CH=C", "[CHX3]=[CX3]"),
    ("C=C", "[CX3]=[CX3]"),
    ("CH2=C=CH", "[CH2X3]=[CX2]=[CHX3]"),
    ("CH2=C=C", "[CH2X3]=[CX2]=[CX3]"),
    ("CH=C=CH", "[CHX3]=[CX2]=[CHX3]"),
    ("CH#C", "[CHX2]#[CX2]"),
    ("C#C", "[CX2]#[CX2]"),
    ("aCH", "[cH]"),
    ("aC fused with aromatic ring", "[c;R2;$(c~a)]"),
    ("aC fused with nonaromatic subring", "[c;R2;$(c~[!a])]"),
    ("aC except as above", "[c;!R2]"),
    ("aN in aromatic ring", "[n]"),
    ("aC-CH3", "c[CH3X4]"),
    ("aC-CH2", "c[CH2X4]"),
    ("aC-CH", "c[CHX4]"),
    ("aC-C", "c[CX4]"),
    ("aC-CH=CH2", "c[CHX3]=[CH2X3]"),
    ("aC-CH=CH", "c[CHX3]=[CHX3]"),
    ("aC-C=CH2", "c[CX3]=[CH2X3]"),
    ("aC-C#CH", "c[CX2]#[CHX2]"),
    ("aC-C#C", "c[CX2]#[CX2]"),
    ("OH", "[OX2H]"),
    ("aC-OH", "c[OX2H]"),
    ("COOH", "[CX3](=O)[OX2H]"),
    ("aC-COOH", "c[CX3](=O)[OX2H]"),
    ("CH3CO", "[CH3X4][CX3]=O"),
    ("CH2CO", "[CH2X4][CX3]=O"),
    ("CHCO", "[CHX4][CX3]=O"),
    ("CCO", "[CX4][CX3]=O"),
    ("aC-CO", "c[CX3]=O"),
    ("CHO", "[CHX3]=O"),
    ("aC-CHO", "c[CHX3]=O"),
    ("CH3COO", "[CH3X4][CX3](=O)[OX2]"),
    ("CH2COO", "[CH2X4][CX3](=O)[OX2]"),
    ("CHCOO", "[CHX4][CX3](=O)[OX2]"),
    ("CCOO", "[CX4][CX3](=O)[OX2]"),
    ("HCOO", "[CHX3](=O)[OX2]"),
    ("aC-COO", "c[CX3](=O)[OX2]"),
    ("aC-OOCH", "c[OX2][CHX3]=O"),
    ("aC-OOC", "c[OX2][CX3]=O"),
    ("COO except as above", "[CX3;$(*[!c])](=O)[OX2;$(*[!c])]"),
    ("CH3O", "[CH3X4][OX2]"),
    ("CH2O", "[CH2X4][OX2]"),
    ("CH-O", "[CHX4][OX2]"),
    ("C-O", "[CX4][OX2]"),
    ("aC-O", "c[OX2]"),
    ("CH2NH2", "[CH2X4][NX3H2]"),
    ("CHNH2", "[CHX4][NX3H2]"),
    ("CNH2", "[CX4][NX3H2]"),
    ("CH3NH", "[CH3X4][NX3H]"),
    ("CH2NH", "[CH2X4][NX3H]"),
    ("CHNH", "[CHX4][NX3H]"),
    ("CH3N", "[CH3X4][NX3]"),
    ("CH2N", "[CH2X4][NX3]"),
    ("aC-NH2", "c[NX3H2]"),
    ("aC-NH", "c[NX3H]"),
    ("aC-N", "c[NX3]"),
    ("NH2 except as above", "[NX3H2;$(*[!c])]"),
    ("CH=N", "[CHX3]=[NX2]"),
    ("C=N", "[CX3]=[NX2]"),
    ("CH2CN", "[CH2X4]C#N"),
    ("CHCN", "[CHX4]C#N"),
    ("CCN", "[CX4]C#N"),
    ("aC-CN", "cC#N"),
    ("CN except as above", "[CX2;$(*[!c])]#N"),
    ("CH2NCO", "[CH2X4]N=C=O"),
    ("CHNCO", "[CHX4]N=C=O"),
    ("CNCO", "[CX4]N=C=O"),
    ("aC-NCO", "cN=C=O"),
    ("CH2NO2", "[CH2X4][NX3+](=O)[O-]"),
    ("CHNO2", "[CHX4][NX3+](=O)[O-]"),
    ("CNO2", "[CX4][NX3+](=O)[O-]"),
    ("aC-NO2", "c[NX3+](=O)[O-]"),
    ("NO2 except as above", "[NX3+;$(*[!c])](=O)[O-]"),
    ("ONO", "[OX2]N=O"),
    ("ONO2", "[OX2][NX3+](~[O-])=O"),
    ("HCON(CH2)2", "[CHX3](=O)N([CH2X4])[CH2X4]"),
    ("HCONHCH2", "[CHX3](=O)[NX3H][CH2X4]"),
    ("CONH2", "[CX3](=O)[NX3H2]"),
    ("CONHCH3", "[CX3](=O)[NX3H][CH3X4]"),
    ("CONHCH2", "[CX3](=O)[NX3H][CH2X4]"),
    ("CON(CH3)2", "[CX3](=O)N([CH3X4])[CH3X4]"),
    ("CONCH3CH2", "[CX3](=O)N([CH3X4])[CH2X4]"),
    ("CON(CH2)2", "[CX3](=O)N([CH2X4])[CH2X4]"),
    ("CONHCO", "[CX3](=O)[NX3H][CX3]=O"),
    ("CONCO", "[CX3](=O)[NX3][CX3]=O"),
    ("aC-CONH2", "c[CX3](=O)[NX3H2]"),
    ("aC-NH(CO)H", "c[NX3H][CHX3]=O"),
    ("aC-N(CO)H", "c[NX3][CHX3]=O"),
    ("aC-CONH", "c[CX3](=O)[NX3H]"),
    ("aC-NHCO", "c[NX3H][CX3]=O"),
    ("aC-NCO", "c[NX3][CX3]=O"),
    ("NHCONH", "[NX3H][CX3](=O)[NX3H]"),
    ("NH2CONH", "[NX3H2][CX3](=O)[NX3H]"),
    ("NH2CON", "[NX3H2][CX3](=O)[NX3]"),
    ("NHCON", "[NX3H][CX3](=O)[NX3]"),
    ("NCON", "[NX3][CX3](=O)[NX3]"),
    ("aC-NHCONH2", "c[NX3H][CX3](=O)[NX3H2]"),
    ("aC-NHCONH", "c[NX3H][CX3](=O)[NX3H]"),
    ("NHCO except as above", "[NX3H;$(*[!c])][CX3;$(*[!c])]=O"),
    ("CH2Cl", "[CH2X4]Cl"),
    ("CHCl", "[CHX4]Cl"),
    ("CCl", "[CX4]Cl"),
    ("CHCl2", "[CHX4](Cl)Cl"),
    ("CCl2", "[CX4](Cl)Cl"),
    ("CCl3", "[CX4](Cl)(Cl)Cl"),
    ("CH2F", "[CH2X4]F"),
    ("CHF", "[CHX4]F"),
    ("CF", "[CX4]F"),
    ("CHF2", "[CHX4](F)F"),
    ("CF2", "[CX4](F)F"),
    ("CF3", "[CX4](F)(F)F"),
    ("CCl2F", "[CX4](Cl)(Cl)F"),
    ("HCClF", "[CHX4](Cl)F"),
    ("CClF2", "[CX4](Cl)(F)F"),
    ("aC-Cl", "cCl"),
    ("aC-F", "cF"),
    ("aC-I", "cI"),
    ("aC-Br", "cBr"),
    ("I- except as above", "[I;$(*[!c])]"),
    ("Br- except as above", "[Br;$(*[!c])]"),
    ("F- except as above", "[F;$(*[!c])]"),
    ("Cl- except as above", "[Cl;$(*[!c])]"),
    ("CHNOH", "[CHX3]=N[OX2H]"),
    ("CNOH", "[CX3]=N[OX2H]"),
    ("aC-CHNOH", "c[CHX3]=N[OX2H]"),
    ("OCH2CH2OH", "[OX2][CH2X4][CH2X4][OX2H]"),
    ("OCHCH2OH", "[OX2][CHX4][CH2X4][OX2H]"),
    ("OCH2CHOH", "[OX2][CH2X4][CHX4][OX2H]"),
    ("-O-OH", "[OX2][OX2H]"),
    ("CH2SH", "[CH2X4][SX2H]"),
    ("CHSH", "[CHX4][SX2H]"),
    ("CSH", "[CX4][SX2H]"),
    ("aC-SH", "c[SX2H]"),
    ("-SH ( except as above)", "[SX2H;$(*[!c])]"),
    ("CH3S", "[CH3X4][SX2]"),
    ("CH2S", "[CH2X4][SX2]"),
    ("CHS", "[CHX4][SX2]"),
    ("CS", "[CX4][SX2]"),
    ("aC-S-", "c[SX2]"),
    ("SO", "[SX3]=O"),
    ("SO2", "[SX4](=O)=O"),
    ("SO3 (sulfite)", "[SX3](=O)([OX2])[OX2]"),
    ("SO3 (sulfonate)", "[SX4](=O)(=O)[OX2]"),
    ("SO4 (sulfate)", "[SX4](=O)(=O)([OX2])[OX2]"),
    ("aC-SO", "c[SX3]=O"),
    ("aC-SO2", "c[SX4](=O)=O"),
    ("PH (phosphine)", "[PX3H]"),
    ("P (phosphine)", "[PX3]"),
    ("PO3 (phosphite)", "[PX3]([OX2])([OX2])[OX2]"),
    ("PHO3 (phosphonate)", "[PX4H](=O)([OX2])[OX2]"),
    ("PO3 (phosphonate)", "[PX4](=O)([OX2])[OX2]"),
    ("PHO4 (phosphate)", "[PX4](=O)([OX2H])([OX2])[OX2]"),
    ("PO4 (phosphate)", "[PX4](=O)([OX2])([OX2])[OX2]"),
    ("aC-PO4", "c[OX2][PX4](=O)([OX2])[OX2]"),
    ("aC-P", "c[P]"),
    ("CO3 (carbonate)", "[CX3](=O)([OX2])[OX2]"),
    ("C2H3O in three member ring", "[O;R]1[CH2;R][CH1;R]1"),
    ("C2H2O in three member ring", ['[O;R]1[CH1;R][CH1;R]1', '[O;R]1[CH2;R][CH0;R]1']),
    ("C2O in three member ring", "[O;R]1[C;R][C;R]1"),
    ("CH2 (cyclic)", "[CH2X4;R]"),
    ("CH (cyclic)", "[CHX4;R]"),
    ("C (cyclic)", "[CX4;R]"),
    ("CH=CH (cyclic)", "[CHX3;R]=[CHX3;R]"),
    ("CH=C (cyclic)", "[CHX3;R]=[CX3;R]"),
    ("C=C (cyclic)", "[CX3;R]=[CX3;R]"),
    ("CH2=C (cyclic)", "[CH2X3]=[CX3;R]"),
    ("NH (cyclic)", "[NH;R]"),
    ("N (cyclic)", "[N;R]"),
    ("CH=N (cyclic)", "[CHX3;R]=[NX2;R]"),
    ("C=N (cyclic)", "[CX3;R]=[NX2;R]"),
    ("O (cyclic)", "[O;R]"),
    ("CO (cyclic)", "[CX3;R]=O"),
    ("S (cyclic)", "[S;R]"),
    ("SO2 (cyclic)", "[SX4;R](=O)=O"),
]