# SMARTS strings must be syntactically correct and #Idk if this is right: use recursive smarts ($ to specify connections to parts that aren't group). Number of Hs and charges are taken literally from smarts strings, so if not no Hs or charge of 0, the smarts must include that.
MARGAN = [
("CH3", "[CX4H3]"),
("CH2", "[CX4H2]"),
("CH", "[CX4H1]"),
("C", "[CX4H0]"),
("CH2=CH", "[CH2]=[CH]"),
("CH=CH", "[CH]=[CH]"),
("CH2=C", "[CH2]=[CX3]"),
("CH=C", "[CH]=[CX3]"),
("C=C", "[CX3]=[CX3]"),
("CH2=C=CH", "[CH2]=[C]=[CH]"),
("CH2=C=C", "[CH2]=[C]=[CX3]"),
("CH=C=CH", "[CH]=[C]=[CH]"),
("CH#C", "[CH]#[C]"),
("C#C", "[CX2]#[CX2]"),
("aCH", "[cH]"),
("aC fused with aromatic ring", "[c;R2;$(c(:a)(:a):a)]"),
("aC fused with nonaromatic subring", "[c;R2;$(c~[!a])]"),
("aC except as above", "[c;R1]"),
("aN in aromatic ring", "[n]"),
("aC-CH3", "c[CX4H3]"),
("aC-CH2", "c[CX4H2]"),
("aC-CH", "c[CX4H1]"),
("aC-C", "c[CX4H0]"),
("aC-CH=CH2", "c[CH]=[CH2]"),
("aC-CH=CH", "c[CH]=[CH]"),
("aC-C=CH2", "c[CX3]=[CH2]"),
("aC-C#CH", "c[C]#[CH]"),
("aC-C#C", "c[C]#[C]"),
("OH", "[OH;$(*[!c])]"),
("aC-OH", "c[OX2H]"),
("COOH", "[CX3;$(*[!c])](=O)[OX2H]"),
("aC-COOH", "c[CX3](=O)[OX2H]"),
("CH3CO", "[CX4H3][CX3](=O)"),
("CH2CO", "[CX4H2][CX3](=O)"),
("CHCO", "[CX4H1][CX3](=O)"),
("CCO", "[CX4H0][CX3](=O)"),
("aC-CO", "c[CX3](=O)"),
("CHO", "[CX3H1;$(*[!c])]=O"),
("aC-CHO", "c[CX3H1]=O"),
("CH3COO", "[CX4H3][CX3](=O)[OX2]"),
("CH2COO", "[CX4H2][CX3](=O)[OX2]"),
("CHCOO", "[CX4H1][CX3](=O)[OX2]"),
("CCOO", "[CX4H0][CX3](=O)[OX2]"),
("HCOO", "[CX3H1](=O)[OX2]"),
("aC-COO", "c[CX3](=O)[OX2]"),
("aC-OOCH", "c[OX2][CX3H1]=O"),
("aC-OOC", "c[OX2][CX3](=O)"),
("COO except as above", "[CX3;$(*[!c])](=O)[OX2;$(*[!c])]"),
("CH3O", "[CX4H3][OX2]"),
("CH2O", "[CX4H2][OX2]"),
("CH-O", "[CX4H1][OX2]"),
("C-O", "[CX4H0][OX2]"),
("aC-O", "c[OX2]"),
("CH2NH2", "[CX4H2][NX3H2]"),
("CHNH2", "[CX4H1][NX3H2]"),
("CNH2", "[CX4H0][NX3H2]"),
("CH3NH", "[CX4H3][NX3H1]"),
("CH2NH", "[CX4H2][NX3H1]"),
("CHNH", "[CX4H1][NX3H1]"),
("CH3N", "[CX4H3][NX3]"),
("CH2N", "[CX4H2][NX3]"),
("aC-NH2", "c[NX3H2]"),
("aC-NH", "c[NX3H1]"),
("aC-N", "c[NX3]"),
("NH2 except as above", "[NX3H2;$(*[!c])]"),
("CH=N", "[CH]=[NX2]"),
("C=N", "[CX3]=[NX2]"),
("CH2CN", "[CX4H2][C]#[N]"),
("CHCN", "[CX4H1][C]#[N]"),
("CCN", "[CX4H0][C]#[N]"),
("aC-CN", "c[C]#[N]"),
("CN except as above", "[C;$(*[!c])]#[N]"),
("CH2NCO", "[CX4H2][NX2]=[C]=[O]"),
("CHNCO", "[CX4H1][NX2]=[C]=[O]"),
("CNCO", "[CX4H0][NX2]=[C]=[O]"),
("aC-NCO", "c[NX2]=[C]=[O]"),
("CH2NO2", "[CX4H2][NX3+](=O)[O-]"),
("CHNO2", "[CX4H1][NX3+](=O)[O-]"),
("CNO2", "[CX4H0][NX3+](=O)[O-]"),
("aC-NO2", "c[NX3+](=O)[O-]"),
("NO2 except as above", "[NX3+;$(*[!c])](=O)[O-]"),
("ONO", "[OX2][NX2]=O"),
("ONO2", "[OX2][NX3+](=O)[OX1-]"),
("HCON(CH2)2", "[CX3H1](=O)N([CX4H2])[CX4H2]"),
("HCONHCH2", "[CX3H1](=O)[NX3H1][CX4H2]"),
("CONH2", "[CX3;$(*[!c])](=O)[NX3H2]"),
("CONHCH3", "[CX3](=O)[NX3H1][CX4H3]"),
("CONHCH2", "[CX3](=O)[NX3H1][CX4H2]"),
("CON(CH3)2", "[CX3](=O)N([CX4H3])[CX4H3]"),
("CONCH3CH2", "[CX3](=O)N([CX4H3])[CX4H2]"),
("CON(CH2)2", "[CX3](=O)N([CX4H2])[CX4H2]"),
("CONHCO", "[CX3](=O)[NX3H1][CX3]=O"),
("CONCO", "[CX3](=O)[NX3][CX3]=O"),
("aC-CONH2", "c[CX3](=O)[NX3H2]"),
("aC-NH(CO)H", "c[NX3H1][CX3H1]=O"),
("aC-N(CO)H", "c[NX3]([CX3H1]=O)"),
("aC-CONH", "c[CX3](=O)[NX3H1]"),
("aC-NHCO", "c[NX3H1][CX3]=O"),
("aC-NCO", "c[NX3][CX3]=O"),
("NHCONH", "[NX3H1;$(*[!c])][CX3](=O)[NX3H1;$(*[!c])]"),
("NH2CONH", "[NX3H2][CX3](=O)[NX3H1]"),
("NH2CON", "[NX3H2][CX3](=O)[NX3]"),
("NHCON", "[NX3H1][CX3](=O)[NX3]"),
("NCON", "[NX3][CX3](=O)[NX3]"),
("aC-NHCONH2", "c[NX3H1][CX3](=O)[NX3H2]"),
("aC-NHCONH", "c[NX3H1][CX3](=O)[NX3H1]"),
("NHCO except as above", "[NX3H1;$(*[!c])][CX3;$(*[!c])](=O)"),
("CH2Cl", "[CX4H2]Cl"),
("CHCl", "[CX4H1]Cl"),
("CCl", "[CX4H0]Cl"),
("CHCl2", "[CX4H1](Cl)Cl"),
("CCl2", "[CX4H0](Cl)Cl"),
("CCl3", "[CX4H0](Cl)(Cl)Cl"),
("CH2F", "[CX4H2]F"),
("CHF", "[CX4H1]F"),
("CF", "[CX4H0]F"),
("CHF2", "[CX4H1](F)F"),
("CF2", "[CX4H0](F)F"),
("CF3", "[CX4H0](F)(F)F"),
("CCl2F", "[CX4H0](Cl)(Cl)F"),
("HCClF", "[CX4H1](Cl)F"),
("CClF2", "[CX4H0](Cl)(F)F"),
("aC-Cl", "cCl"),
("aC-F", "cF"),
("aC-I", "cI"),
("aC-Br", "cBr"),
("I- except as above", "[I;!$(*c)]"),
("Br- except as above", "[Br;!$(*c)]"),
("F- except as above", "[F;!$(*c)]"),
("Cl- except as above", "[Cl;!$(*c)]"),
("CHNOH", "[CH]=[NX2][OX2H]"),
("CNOH", "[CX3]=[NX2][OH]"),
("aC-CHNOH", "c[CH]=[NX2][OX2H]"),
("OCH2CH2OH", "[OX2][CH2][CH2][OX2H]"),
("OCHCH2OH", "[OX2][CH]([CH2][OX2H])"),
("OCH2CHOH", "[OX2][CH2][CH]([OX2H])"),
("-O-OH", "[OX2][OX2H]"),
("CH2SH", "[CX4H2][SX2H]"),
("CHSH", "[CX4H1][SX2H]"),
("CSH", "[CX4H0][SX2H]"),
("aC-SH", "c[SX2H]"),
("-SH ( except as above)", "[SX2H;$(*[!c])]"),
("CH3S", "[CX4H3][SX2]"),
("CH2S", "[CX4H2][SX2]"),
("CHS", "[CX4H1][SX2]"),
("CS", "[CX4H0][SX2]"),
("aC-S-", "c[SX2]"),
("SO", "[SX3;$(*[!c])](=O)"),
("SO2", "[SX4;$(*[!c])](=O)(=O)"),
("SO3 (sulfite)", "O=S([O;$(*[#6])])[O;$(*[#6])]"),
("SO3 (sulfonate)", "[S;$(*[#6])](=O)(=O)[O;$(*[#6])]"),
("SO4 (sulfate)", "O=[S](=O)([O;$(*[#6])])[O;$(*[#6])]"),
("aC-SO", "c[SX3](=O)"),
("aC-SO2", "c[SX4](=O)(=O)"),
("PH (phosphine)", "[PH1]"),
("P (phosphine)", "[PH0]"),
("PO3 (phosphite)", "[P]([O;$(*[#6])])([O;$(*[#6])])[O;$(*[#6])]"),
("PHO3 (phosphonate)", "[PH1](=O)(O)O"),
("PO3 (phosphonate)", "[P;$(*[#6])](=O)([O;$(*[#6])])[O;$(*[#6])]"),
("PHO4 (phosphate)", "O[P](=O)([OH1])O"),
("PO4 (phosphate)", "O=[P]([O;$(*[#6])])([O;$(*[#6])])[O;$(*[#6])]"),
("aC-PO4", "c[OX2H0]P(=O)(O)(O)"),
("aC-P", "cP"),
("CO3 (carbonate)", "O=[C]([O;$(*[#6])])[O;$(*[#6])]"),
("C2H3O", "[O;R]1[CH1;R][CH2;R]1"),
("C2H2O", ["[O;R]1[CH2;R][CH0;R]1", "[O;R]1[CH1;R][CH1;R]1"]),
("C2O", "[OX2;R]1[CH1X4;R][CX4;R]1"),
("CH2 (cyclic)", "[CH2;R]"),
("CH (cyclic)", "[CH;R]"),
("C (cyclic)", "[C;R]"),
("CH=CH (cyclic)", "[CH;R]=[CH;R]"),
("CH=C (cyclic)", "[CH;R]=[C;R]"),
("C=C (cyclic)", "[C;R]=[C;R]"),
("CH2=C (cyclic)", "[CH2]=[C;R]"),
("NH (cyclic)", "[NH;R]"),
("N (cyclic)", "[N;R]"),
("CH=N (cyclic)", "[CH;R]=[N;R]"),
("C=N (cyclic)", "[C;R]=[N;R]"),
("O (cyclic)", "[O;R]"),
("CO (cyclic)", "[C;R]=O"),
("S (cyclic)", "[S;R]"),
("SO2 (cyclic)", "[S;R](=O)=O"),
]